declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    QApp: typeof import('quasar')['QApp']
    QLayout: typeof import('quasar')['QLayout']
    QHeader: typeof import('quasar')['QHeader']
    QToolbar: typeof import('quasar')['QToolbar']
    QBtn: typeof import('quasar')['QBtn']
    QBtnGroup: typeof import('quasar')['QBtnGroup']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QSelect: typeof import('quasar')['QSelect']
    QTable: typeof import('quasar')['QTable']
    QTd: typeof import('quasar')['QTd']
    QTh: typeof import('quasar')['QTh']
    QTr: typeof import('quasar')['QTr']
    QChip: typeof import('quasar')['QChip']
    QDialog: typeof import('quasar')['QDialog']
    QMenu: typeof import('quasar')['QMenu']
    QList: typeof import('quasar')['QList']
    QItem: typeof import('quasar')['QItem']
    QItemSection: typeof import('quasar')['QItemSection']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QSeparator: typeof import('quasar')['QSeparator']
    QSpace: typeof import('quasar')['QSpace']
    QAvatar: typeof import('quasar')['QAvatar']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QInnerLoading: typeof import('quasar')['QInnerLoading']
    QTooltip: typeof import('quasar')['QTooltip']
    QBadge: typeof import('quasar')['QBadge']
    QSpinner: typeof import('quasar')['QSpinner']
    QLinearProgress: typeof import('quasar')['QLinearProgress']
  }
}

export {}
