name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: cd frontend && npm ci
        
      - name: Build
        run: cd frontend && npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES_CUSTOM_DOMAIN: true
          VITE_API_URL: https://stock-manager-backend.up.railway.app/api
          
      - name: Verify build output
        run: |
          echo "Build output contents:"
          ls -la frontend/dist/
          echo "CNAME file contents:"
          cat frontend/dist/CNAME || echo "CNAME file not found"
          echo "Index.html exists:"
          ls -la frontend/dist/index.html || echo "index.html not found"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend/dist

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
